meta-ti-foundational: ti-apps-launcher: Fix build errors on some hosts
Below build error was seen on some host machines:

ERROR: ti-apps-launcher-1.0-r19:
recipe-sysroot-native/usr/libexec/rcc: error while loading shared libraries: libQt6Core.so.6: cannot open shared object file: No such file or directory

Issue appears when building this app inside of a docker, over certain
host machines. The ABI tag in the .so denotes the minimum kernel version
required before loading the file. Since Docker has no own kernel, the
Docker host's kernel is used for that comparison [0].

Add the mentioned workaround here to strip the ABI tag. Qt seems to have
fallback code, so nothing breaks.

[0]: https://forum.qt.io/topic/136058/libqt6core-so-6-cannot-open-shared-object-file-even-though-it-exists-seems-to-depend-on-docker-host-os

Signed-off-by: Aniket Limaye <a-limaye@ti.com>